In [ ]:
print("Learning Pytorch")

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


#Introduction to Tensors

#Creating Tensors

In [3]:
#Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
#Dimentions
scalar.ndim


0

In [7]:
scalar.item()

7

In [8]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,5,6],
                      [8,5,2]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 6],
         [8, 5, 2]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [8, 5, 2]])

The output torch.Size([1, 3, 3]) for the tensor [[[1, 2, 3], [3, 5, 6], [8, 5, 2]]] might seem a little counter-intuitive at first.

Here's how to break it down:

The first dimension (size 1) represents the outermost set of square brackets [[...]]. There's only one of these main groups in your tensor.
The second dimension (size 3) represents the number of lists within that outermost group. In your tensor, you have three inner lists: [1, 2, 3], [3, 5, 6], and [8, 5, 2].
The third dimension (size 3) represents the number of elements within each of those inner lists. Each of your inner lists has three numbers.
So, torch.Size([1, 3, 3]) means you have 1 block of data, and within that block, you have a 3x3 structure. This is a 3-dimensional tensor.