<a href="https://colab.research.google.com/github/Hanzlase/Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Learning Pytorch")

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


#Introduction to Tensors

#Creating Tensors

In [3]:
#Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
#Dimentions
scalar.ndim


0

In [7]:
scalar.item()

7

In [8]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [3,5,6],
                      [8,5,2]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 6],
         [8, 5, 2]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [8, 5, 2]])

The output torch.Size([1, 3, 3]) for the tensor [[[1, 2, 3], [3, 5, 6], [8, 5, 2]]] might seem a little counter-intuitive at first.

Here's how to break it down:

The first dimension (size 1) represents the outermost set of square brackets [[...]]. There's only one of these main groups in your tensor.
The second dimension (size 3) represents the number of lists within that outermost group. In your tensor, you have three inner lists: [1, 2, 3], [3, 5, 6], and [8, 5, 2].
The third dimension (size 3) represents the number of elements within each of those inner lists. Each of your inner lists has three numbers.
So, torch.Size([1, 3, 3]) means you have 1 block of data, and within that block, you have a 3x3 structure. This is a 3-dimensional tensor.

###Random Tensors
why Random tesnors?
We use random tensors in PyTorch mostly to give our machine learning models a random starting point. Think of it like shuffling a deck of cards before a game it makes sure things aren't predictable from the start and helps the model learn better. They're also handy for making fake data when we just want to test things out.


"Start with Random numbers -> look at data -> update random numbers -> look at data -> update random numbers."

In [20]:
#Create a Random tensor of shape(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4142, 0.9099, 0.6929, 0.4534],
        [0.2394, 0.3081, 0.4836, 0.0519],
        [0.7292, 0.8434, 0.1559, 0.4692]])

In [21]:
random_tensor.ndim


2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [27]:
#Create a Random tensor with similar shape to an image tensor
rand_img_size_tensor=torch.rand(size=(224,224,3))
rand_img_size_tensor.shape,rand_img_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

#Zeros and Ones

In [28]:
#Create a tensor of all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
#Create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_tensor.dtype

torch.float32

#Creating a range of tensors and tensors-like



In [41]:
#Use torch.range()
one_to_ten=torch.arange(start=0,end=11,step=2) # OR one_to_ten=torch.arange(0,11)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [42]:
#creating tensors like
ten_zeros=torch.zeros_like(input =one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

#Tensor Datatype

In [44]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,#automatically sets it to float32
                             device=None,#will be created on CPU
                             requires_grad=False) #Don't bother keeping track of the steps needed to calculate gradients for this specific tensor.
float_32_tensor

tensor([3., 6., 9.])

In [47]:
#convert to 16
float_16_tensor=float_32_tensor.type(torch.float16)

In [48]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [49]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [50]:
#we can multiply tensors with different datatypes
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [51]:
#create a tensor
some_tensor=torch.rand(4,5)
some_tensor

tensor([[0.3828, 0.9516, 0.6282, 0.9990, 0.7637],
        [0.5475, 0.6896, 0.5418, 0.0997, 0.2655],
        [0.6679, 0.9851, 0.2571, 0.1209, 0.4318],
        [0.1122, 0.7624, 0.4357, 0.1027, 0.1091]])

In [53]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3828, 0.9516, 0.6282, 0.9990, 0.7637],
        [0.5475, 0.6896, 0.5418, 0.0997, 0.2655],
        [0.6679, 0.9851, 0.2571, 0.1209, 0.4318],
        [0.1122, 0.7624, 0.4357, 0.1027, 0.1091]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 5])
Device tensor is on: cpu


#Tensor Manipulation


In [55]:
# Create a tensor
my_tensor = torch.tensor([1, 2, 3, 4, 5])

# Add 10 to the tensor
tensor_plus_10 = my_tensor + 10

print(f"Original tensor: {my_tensor}")
print(f"Tensor after adding 10: {tensor_plus_10}")

Original tensor: tensor([1, 2, 3, 4, 5])
Tensor after adding 10: tensor([11, 12, 13, 14, 15])


In [56]:
# Multiply the tensor by 10
tensor_times_10 = my_tensor * 10

print(f"Original tensor: {my_tensor}")
print(f"Tensor after multiplying by 10: {tensor_times_10}")

Original tensor: tensor([1, 2, 3, 4, 5])
Tensor after multiplying by 10: tensor([10, 20, 30, 40, 50])


In [57]:
# Subtract 10 from the tensor
tensor_minus_10 = my_tensor - 10

print(f"Original tensor: {my_tensor}")
print(f"Tensor after subtracting 10: {tensor_minus_10}")

Original tensor: tensor([1, 2, 3, 4, 5])
Tensor after subtracting 10: tensor([-9, -8, -7, -6, -5])


In [58]:
# Create a tensor
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([6, 7, 8, 9, 10])

# Element-wise addition using torch.add()
addition_result = torch.add(tensor_a, tensor_b)
print(f"Element-wise addition using torch.add(): {addition_result}")

# Element-wise multiplication using torch.mul()
multiplication_result = torch.mul(tensor_a, tensor_b)
print(f"Element-wise multiplication using torch.mul(): {multiplication_result}")

# Element-wise subtraction using torch.sub()
subtract_result = torch.sub(tensor_b, tensor_a)
print(f"Element-wise subtraction using torch.sub(): {subtract_result}")

# Element-wise division using torch.div()
division_result = torch.div(tensor_b, tensor_a)
print(f"Element-wise division using torch.div(): {division_result}")

Element-wise addition using torch.add(): tensor([ 7,  9, 11, 13, 15])
Element-wise multiplication using torch.mul(): tensor([ 6, 14, 24, 36, 50])
Element-wise subtraction using torch.sub(): tensor([5, 5, 5, 5, 5])
Element-wise division using torch.div(): tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])


In [59]:
# Create two tensors for matrix multiplication
tensor_matrix_a = torch.tensor([[1, 2],
                                 [3, 4]])

tensor_matrix_b = torch.tensor([[5, 6],
                                 [7, 8]])

# Perform matrix multiplication using torch.matmul()
matrix_mult_result = torch.matmul(tensor_matrix_a, tensor_matrix_b)
print(f"Matrix A:\n{tensor_matrix_a}")
print(f"Matrix B:\n{tensor_matrix_b}")
print(f"Result of matrix multiplication:\n{matrix_mult_result}")

# Alternatively, use the @ operator
matrix_mult_result_alt = tensor_matrix_a @ tensor_matrix_b
print(f"\nResult of matrix multiplication (using @ operator):\n{matrix_mult_result_alt}")

Matrix A:
tensor([[1, 2],
        [3, 4]])
Matrix B:
tensor([[5, 6],
        [7, 8]])
Result of matrix multiplication:
tensor([[19, 22],
        [43, 50]])

Result of matrix multiplication (using @ operator):
tensor([[19, 22],
        [43, 50]])


In [68]:
%%time
val=0
for i in range(len(tensor_a)):
  val+=tensor_a[i]*tensor_b[i]
print(val)

tensor(130)
CPU times: user 1.74 ms, sys: 0 ns, total: 1.74 ms
Wall time: 1.52 ms


In [69]:
#Far faster than For loop
%%time
torch.matmul(tensor_a,tensor_b)


CPU times: user 96 µs, sys: 4 µs, total: 100 µs
Wall time: 106 µs


tensor(130)